apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Application components (microservices)
# Sync wave 4

resources:
# Application configuration
- configmap.yaml

# Application services
- ingester.knative.yaml
- processor.knative.yaml
- ui.knative.yaml
