apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camelquarkusvoter-application
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubefiles/base/application
    repoURL: https://github.com/kdubois/camelquarkusvoter.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

# Made with Bob
