---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cameldemo-ingester
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: cameldemo-ingester
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cameldemo-ingester
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: cameldemo-ingester
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cameldemo-ingester
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/part-of: cameldemo
      annotations:
        autoscaling.knative.dev/target: '2'
        autoscaling.knative.dev/targetUtilizationPercentage: '70'
        autoscaling.knative.dev/window: 60s
    spec:
      containerConcurrency: 1
      containers:
        - image: quay.io/kevindubois/cameldemo-ingester
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 0
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: cameldemo-ingester
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 0
              scheme: HTTP            
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: cameldemo-ingester
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cameldemo-ingester-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: cameldemo-ingester
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cameldemo-ingester-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    name: cameldemo-ingester
