---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: cameldemo-ui
  name: cameldemo-ui
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: cameldemo-ui
    app.kubernetes.io/part-of: cameldemo
  name: cameldemo-ui
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: cameldemo-ui
      annotations:
        autoscaling.knative.dev/target: '1'
        autoscaling.knative.dev/targetUtilizationPercentage: '70'
        autoscaling.knative.dev/window: 60s
    spec:
      containerConcurrency: 1
      containers:
        - image: quay.io/kevindubois/cameldemo-ui
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 0
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: cameldemo-ui
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 0
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: cameldemo-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cameldemo-ui-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: cameldemo-ui
