apiVersion: v1
kind: ConfigMap
metadata:
  name: appconfig
data:
  KAFKA_BOOTSTRAP_SERVERS: "EXAMPLE-cluster-kafka-bootstrap:9092"
  DB_SERVER: "quarkus"
  ingester_url: "YOUR_CONSUMER_URL"
  processor_url: "YOUR_PROCESSOR_URL"