apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camelquarkusvoter
  namespace: openshift-gitops 
spec:
  destination:
    namespace: cameldemo
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: kubefiles
    repoURL: https://github.com/kdubois/camelquarkusvoter.git
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true