apiVersion: v1
kind: ConfigMap
metadata:
  name: appconfig
data:
  kafka.bootstrap.servers: "EXAMPLE-cluster-kafka-bootstrap:9092"
  consumer.url: "YOUR_CONSUMER_URL"
  processor.url: "YOUR_PROCESSOR_URL"