apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: canary

resources:
- ingester.knative.yaml
- processor.knative.yaml
- ui.knative.yaml
- configs/configmap.yaml
- configs/secrets.yaml



